eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9401/eureka
server:
  port: 9405
spring:
  application:
    name: consumer
opentracing:
  jaeger:
    enabled: true
    log-spans: true
    const-sampler:
      decision: true
    udp-sender:
      host: localhost
      port: 6831