eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://localhost:9401/eureka/
server:
  port: 9402
spring:
  application:
    name: provide
opentracing:
  jaeger:
    enabled: true
    log-spans: true
    const-sampler:
      decision: true
    udp-sender:
      host: localhost
      port: 6831
